name: Scheduled destroyer

on:
  #schedule:
  #  - cron: '00 18 * * *'
  workflow_dispatch:

env:
  BRANCH_NAME: deployed

jobs:
  recreate-branch:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: develeopment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0
          ref: main

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
      - name: remove deploy branch
        continue-on-error: true
        run: |
          git push origin --delete $BRANCH_NAME
      - name: recreate deploy branch
        run: |
          git push -u origin $BRANCH_NAME

